<?php

use function Livewire\Volt\{title};

title('TeamsBot - Übersicht');

?>

<div>
<x-intranet-app-teams-bot::teams-bot-layout heading="TeamsBot App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-teams-bot::teams-bot-layout>
</div>